# docker compose's version
version: '3'
services:
  redis-server:
    image: 'redis'
  node-app:
    # look in the current directory to build container using a dockerfile
    build: .
    ports:
      - '4001:8081'
      # my machine : docker container
